### ISSUE TITLE
Error: could not detect network

### ISSUE THREAD

**Issue by kingjoydog** [ericet/claystack#1]
/claystack/claystack/node_modules/@ethersproject/logger/lib/index.js:199 
var error = new Error(message);
                    ^

Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.1)

**Comment by kingjoydog** [comment]
详细错误如下
/claystack/claystack/node_modules/@ethersproject/logger/lib/index.js:199
        var error = new Error(message);
                    ^

Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.1)
    at Logger.makeError (/claystack/claystack/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Logger.throwError (/claystack/claystack/node_modules/@ethersproject/logger/lib/index.js:208:20)
    at JsonRpcProvider.<anonymous> (/claystack/claystack/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:517:54)
    at step (/claystack/claystack/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/claystack/claystack/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/claystack/claystack/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}

Node.js v17.0.1

**Comment by ericet** [comment]
代码里面的API由于太多人使用，导致请求超了，你可以替换一下那个API。用这个：https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
或者去https://www.alchemy.com/申请一个

**Comment by kingjoydog** [comment]
> 
老哥🐂

**Comment by ericet** [comment]
更新了一下readme和API

**Comment by lk583998442** [comment]
自己申请的接口有点不稳定呀

**Comment by ericet** [comment]
用pm2 进程管理工具。这样程序挂了，会自动重启
安装是: 
* npm install pm2 -g
启动：
* npm start claim.js
停止:
* npm stop claim
重启:
* npm restart claim

**Comment by lk583998442** [comment]
可以了 谢谢老板

**Comment by lk583998442** [comment]
老板 POAP那个不能用了吗

**Comment by ericet** [comment]
不行了 他们加了google验证

**Comment by lk583998442** [comment]
大佬 有没有方法检测下每个账号需要哪五个币以及数量   以便快速筛选出需要数量少的进行激活 谢谢

**Comment by ericet** [comment]
可以查出哪五种币，但是要知道所需的币的数量需要知道币的价格。币的价格不知道他们哪里来的

**Comment by lk583998442** [comment]
不折腾了 卷不动了 搞了几个号
 今天项目方把领取一次价格提到0.2eth 测试币都内卷了 搞不动了
